CREATE TABLE IF NOT EXISTS vehicles (
    id SERIAL PRIMARY KEY,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    year INTEGER,
    VClass VARCHAR(100),
    trany VARCHAR(100),
    drive VARCHAR(100),
    displ NUMERIC(4,1),
    cylinders INTEGER,
    fuelType1 VARCHAR(100),
    fuelType2 VARCHAR(100),
    city08 NUMERIC(5,1),
    highway08 NUMERIC(5,1),
    comb08 NUMERIC(5,1),
    cityA08 NUMERIC(5,1),
    highwayA08 NUMERIC(5,1),
    combA08 NUMERIC(5,1),
    startStop VARCHAR(1),
    sCharger VARCHAR(1),
    tCharger VARCHAR(1),
    phevBlended BOOLEAN,
    phevCity NUMERIC(5,1),
    phevHwy NUMERIC(5,1),
    phevComb NUMERIC(5,1),
    co2 INTEGER,
    co2A INTEGER,
    ghgScore INTEGER,
    ghgScoreA INTEGER
);

